package com.ahtohiofilho.dominopernambucano.miniproduction

internal data class SyntheticProfile(
    val index: Int,
    val publicDisplayName: String,
    val tableCode: String,
)

internal val syntheticRoster: List<SyntheticProfile> = listOf(
    SyntheticProfile(1, "João Alves", "JAL"),
    SyntheticProfile(2, "Marina Costa", "MCO"),
    SyntheticProfile(3, "Rafael Lima", "RLI"),
    SyntheticProfile(4, "Camila Rocha", "CRO"),
    SyntheticProfile(5, "Bruno Melo", "BME"),
    SyntheticProfile(6, "Larissa Nunes", "LNU"),
    SyntheticProfile(7, "Diego Ramos", "DRA"),
    SyntheticProfile(8, "Paula Freitas", "PFR"),
    SyntheticProfile(9, "Tiago Barros", "TBA"),
    SyntheticProfile(10, "Renata Moura", "RMO"),
    SyntheticProfile(11, "André Sales", "ASA"),
    SyntheticProfile(12, "Bianca Torres", "BTO"),
    SyntheticProfile(13, "Felipe Castro", "FCA"),
    SyntheticProfile(14, "Aline Gomes", "AGO"),
    SyntheticProfile(15, "Lucas Dantas", "LDA"),
    SyntheticProfile(16, "Natália Pires", "NPI"),
    SyntheticProfile(17, "Márcio Tavares", "MTA"),
    SyntheticProfile(18, "Sofia Correia", "SCO"),
    SyntheticProfile(19, "Gustavo Leal", "GLE"),
    SyntheticProfile(20, "Helena Braga", "HBR"),
    SyntheticProfile(21, "Eduardo Farias", "EFA"),
    SyntheticProfile(22, "Juliana Prado", "JPR"),
    SyntheticProfile(23, "Caio Mendes", "CME"),
    SyntheticProfile(24, "Isabela Duarte", "IDU"),
    SyntheticProfile(25, "Rodrigo Azevedo", "RAZ"),
    SyntheticProfile(26, "Fernanda Lopes", "FLO"),
    SyntheticProfile(27, "Mateus Vieira", "MVI"),
    SyntheticProfile(28, "Débora Martins", "DMA"),
    SyntheticProfile(29, "Vinícius Paiva", "VPA"),
    SyntheticProfile(30, "Carolina Neves", "CNE"),
    SyntheticProfile(31, "Leandro Peixoto", "LPE"),
    SyntheticProfile(32, "Amanda Ribeiro", "ARI"),
    SyntheticProfile(33, "Henrique Moraes", "HMO"),
    SyntheticProfile(34, "Beatriz Coelho", "BCO"),
    SyntheticProfile(35, "Murilo Cardoso", "MCA"),
    SyntheticProfile(36, "Patrícia Teixeira", "PTE"),
    SyntheticProfile(37, "Igor Vasconcelos", "IVA"),
    SyntheticProfile(38, "Letícia Araújo", "LAR"),
    SyntheticProfile(39, "Daniel Pontes", "DPO"),
    SyntheticProfile(40, "Gabriela Rezende", "GRE"),
    SyntheticProfile(41, "Samuel Cavalcanti", "SCA"),
    SyntheticProfile(42, "Mônica Figueiredo", "MFI"),
    SyntheticProfile(43, "Arthur Queiroz", "AQZ"),
    SyntheticProfile(44, "Priscila Monteiro", "PMO"),
    SyntheticProfile(45, "Vitor Santana", "VSA"),
    SyntheticProfile(46, "Raquel Macedo", "RMA"),
    SyntheticProfile(47, "César Albuquerque", "CAL"),
    SyntheticProfile(48, "Luana Batista", "LBA"),
    SyntheticProfile(49, "Fábio Moreira", "FMO"),
    SyntheticProfile(50, "Tainá Oliveira", "TOL"),
    SyntheticProfile(51, "Alexandre Guimarães", "AGU"),
    SyntheticProfile(52, "Cláudia Reis", "CRE"),
    SyntheticProfile(53, "Jorge Matos", "JMA"),
    SyntheticProfile(54, "Elaine Barbosa", "EBA"),
    SyntheticProfile(55, "Wesley Fernandes", "WFE"),
    SyntheticProfile(56, "Cristina Andrade", "CAN"),
    SyntheticProfile(57, "Otávio Cunha", "OCU"),
    SyntheticProfile(58, "Michele Pacheco", "MPA"),
    SyntheticProfile(59, "Renan Brito", "RBR"),
    SyntheticProfile(60, "Vanessa Silveira", "VSI"),
)
