**

!gradlew
!gradlew.bat
!settings.gradle.kts
!build.gradle.kts
!gradle.properties
!gradle/
!gradle/**
!game-core/
!game-core/**
!miniproduction-client/
!miniproduction-client/**
!Dockerfile.synthetic-population

**/.gradle/
**/.kotlin/
**/build/
**/src/test/
**/local.properties
**/*.jks
**/*.keystore
**/*.p12
**/*.pfx
**/*.pem
**/*.key
**/.env
**/.env.*
