**

!gradlew
!gradlew.bat
!settings.gradle.kts
!build.gradle.kts
!gradle.properties
!gradle/
!gradle/**
!game-core/
!game-core/**
!server/
!server/**
!Dockerfile.server

**/.gradle/
**/.kotlin/
**/build/
**/src/test/
**/local.properties
**/*.jks
**/*.keystore
**/*.p12
**/*.pfx
**/*.pem
**/*.key
**/.env
**/.env.*
